AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'Dangerfile'
    - '.circleci/**/*'
    - '.rubocop.yml'
    - 'Gemfile'
    - 'Gemfile.lock'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
