version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.2.15
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: rpg_seznamka_test
      - image: circleci/postgres:10.15
        environment:
          POSTGRES_DB: rpg_seznamka_test
          POSTGRES_USER: rpg_seznamka_test
          POSTGRES_HOST_AUTH_METHOD: trust
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install new bundler
          command: gem install bundler:2.2.15
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: yarn install
      - run: bundle exec rails db:schema:load --trace
      - run:
          name: Tests
          command: bundle exec rspec


  done:
    docker:
      - image: cimg/ruby:2.7.2-node
    executor: ruby/default
    steps:
      - curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"
