default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: rpg_seznamka_development

test:
  <<: *default
  database: rpg_seznamka_test
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: rpg_seznamka_production
